version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: 1407
       POSTGRES_DB: historygame
     ports:
       - 5435:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
